# Generated by Django 3.2.9 on 2021-11-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student_name',
        ),
    ]
