# Generated by Django 3.2.9 on 2021-11-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_present_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='present_status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_absent',
            field=models.ManyToManyField(blank=True, null=True, related_name='absent', to='attendance.Student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_present',
            field=models.ManyToManyField(blank=True, null=True, related_name='present', to='attendance.Student'),
        ),
    ]
