# Generated by Django 3.2.9 on 2021-11-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20211126_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_absent',
            field=models.ManyToManyField(blank=True, null=True, related_name='is_absent', to='attendance.Student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.ManyToManyField(blank=True, null=True, related_name='is_present', to='attendance.Student'),
        ),
    ]
